version: '3.8'

services:

  jenkins:
    image: bah-jenkins
    container_name: jenkins
    privileged: true
    user: root
    env_file:
      - jenkins-vars.env
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_CMD}:/usr/local/bin/docker

volumes:
  jenkins-data:
