version: '3.8'

services:

  main:
    image: bah-jenkins
    ports:
      - 8080:8080
      - 50000:50000
    secrets:
      - jenkins-user
      - jenkins-pass
      - databricks-workspace
      - databricks-token

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true
  databricks-workspace:
    external: true
  databricks-token:
    external: true
